Comparing performance with lists

In [1]:
N = 100000000

In [2]:
%%timeit
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

4.64 s ± 86.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
list_ = list(range(N))
list_ = [item * item for item in list_]

4.7 s ± 210 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%%timeit
list_ = list(range(N))
list_ = map(lambda x: x*x, list_)

771 ms ± 20.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%%timeit
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

3.78 s ± 60.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%%timeit 
list_ = list(range(N))
list_sum = sum(list_)

2.07 s ± 203 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
import numpy as np

In [10]:
%%timeit 
arr = np.arange(N)
arr = arr * arr

300 ms ± 26.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%%timeit 
arr = np.arange(N)
arr = np.sum(arr)

104 ms ± 11.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
arr = np.arange(5)
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([0,2,4,6,8])
print(arr,type(arr))

[0 2 4 6 8] <class 'numpy.ndarray'>


In [18]:
arr

array([0, 2, 4, 6, 8])

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr.ndim

1

In [21]:
arr.shape

(5,)

In [22]:
arr.size

5

In [23]:
arr.itemsize

8

In [24]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d.ndim

2

In [27]:
arr2d.shape

(2, 3)

In [28]:
arr2d.size

6

In [30]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [31]:
arr3d.ndim

3

In [32]:
arr3d.shape 

(2, 2, 3)

In [33]:
arr3d.size

12

In [35]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
1729 * np.ones((2,3,4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [37]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
np.random.randn(2,3)

array([[ 0.88953809, -0.08248662,  0.25659701],
       [-0.26725519, -0.23303343,  0.85922141]])

In [39]:
np.random.rand(2,3)

array([[0.46025177, 0.66239572, 0.32973921],
       [0.0036877 , 0.04874423, 0.66112518]])

In [40]:
np.random.randint(0,100,(2,3))

array([[41, 92, 64],
       [14,  2, 23]])

In [41]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [42]:
np.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

Indexing

In [44]:
arr3d[1,0,2]

9

In [45]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr3d[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [47]:
arr3d[:,:,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [48]:
np.random.randint(0,10,(5))

array([8, 3, 8, 2, 7])

File Handling

In [52]:
planets_small = np.loadtxt('datasets/planets_small.txt',skiprows=1,usecols=(1,2,3,4,5,6,7,8,9))

In [53]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [57]:
planets_small.shape

(3, 9)

Stats with NumPy

In [58]:
arr = np.random.rand(100000,)

In [59]:
np.amin(arr)

3.493701402912386e-05

In [60]:
np.amax(arr)

0.9999948660549435

In [61]:
np.mean(arr)

0.4997600321431291

In [62]:
np.var(arr)

0.08352168367900836

In [63]:
np.std(arr)

0.289001182833234

In [64]:
np.median(arr)

0.49869084829101507

In [65]:
np.percentile(arr,50)

0.49869084829101507

In [66]:
np.percentile(arr,10)

0.100020298703442

In [67]:
np.percentile(arr,90)

0.9009225433734748

In [69]:
iqr = np.percentile(arr,75) - np.percentile(arr, 25)
print(iqr)

0.5024818183289321


In [71]:
quartiles = np.percentile(arr,[25,75])
iqr = quartiles[1] - quartiles[0]
print(iqr)

0.5024818183289321


In [72]:
(arr - np.mean(arr))/np.std(arr)

array([ 0.778452  , -0.02600641, -0.31702667, ..., -1.59493954,
       -0.22545913,  1.13426442])

In [73]:
arr1 = np.random.randint(50,80,100)
arr2 = np.random.randint(150,185,100)
arr3 = np.random.randint(17,22,100)

np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [78]:
arr2d = np.vstack((arr1,arr2,arr3))

In [81]:
arr2d

array([[ 74,  55,  53,  74,  64,  72,  79,  52,  56,  65,  68,  60,  75,
         77,  62,  65,  65,  61,  75,  75,  75,  50,  50,  69,  64,  55,
         55,  66,  64,  71,  65,  51,  64,  56,  76,  53,  77,  51,  69,
         79,  78,  79,  73,  68,  59,  53,  59,  53,  53,  73,  61,  64,
         61,  61,  67,  73,  51,  57,  71,  51,  52,  79,  54,  52,  51,
         69,  74,  78,  72,  75,  52,  52,  56,  59,  61,  58,  68,  67,
         55,  50,  57,  79,  71,  54,  76,  79,  77,  65,  55,  79,  68,
         67,  50,  59,  68,  54,  54,  52,  77,  62],
       [153, 177, 183, 181, 170, 159, 156, 170, 159, 165, 182, 172, 176,
        156, 165, 174, 152, 161, 172, 160, 153, 156, 169, 179, 154, 164,
        164, 151, 151, 173, 169, 184, 164, 174, 157, 169, 179, 172, 159,
        170, 173, 167, 179, 171, 168, 160, 168, 159, 150, 181, 184, 150,
        161, 157, 172, 172, 161, 175, 181, 166, 179, 153, 179, 166, 160,
        181, 161, 174, 181, 164, 159, 156, 175, 177, 169, 180, 151, 16

In [83]:
np.amin(arr2d,axis=1)

array([ 50, 150,  17])

In [80]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [82]:
np.mean(arr2d,axis=1)

array([ 63.89, 167.21,  18.99])

In [ ]:
cric_data = np.loadtxt('datasets/cric_data.tsv',skiprows=1)

1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has scored a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean for Sachin's scores based on which quartile India's score falls in
7.   For every match find out who has has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on average after having scored x runs
9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...

In [87]:
cric_data.shape

(225, 4)

In [88]:
cric_data = cric_data[:,[1,2,3]]

In [90]:
sachin = cric_data[:,0]
rahul = cric_data[:,1]
india = cric_data[:,2]

In [91]:
def stats(col):
    print("Mean",np.mean(col))
    print('Median',np.median(col))
    print('IQR',np.percentile(col,75) - np.percentile(col,25))

In [92]:
stats(sachin)

Mean 39.87555555555556
Median 27.0
IQR 57.0


In [93]:
stats(rahul)

Mean 32.062222222222225
Median 22.0
IQR 46.0


In [94]:
stats(india)

Mean 220.79555555555555
Median 216.0
IQR 98.0


In [95]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [96]:
sachin.shape

(225,)

In [97]:
sachin.reshape(9,25)

array([[100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
          4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
        138.,  38.,   2.],
       [ 46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,   1.,  41.,  11.,
          3., 186.,  11.,  27.,  27.,  51.,  18.,  32., 146.,   5.,  45.,
        141.,  12.,  65.],
       [ 27.,   7.,  16.,   2.,  28.,   6., 123., 120.,   7.,   3.,   0.,
         81.,   2.,  54., 122.,   4.,  14.,   0., 100.,  15.,   0.,  57.,
         99.,  37.,  38.],
       [ 32.,  21.,  32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,
         37.,  89.,   4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,
         93.,  45.,  26.],
       [  0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,   0.,
         81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,  69.,
         13.,  97.,  93.],
       [  2.,  36.,  39.,   2.,  29.,  12.,  19.,  34.,   2., 100.,  44.,
         82.,   0.,  79.,   6.,   9.,   8.,  23.,  

In [98]:
sachin_by_25s = sachin.reshape(9,25)
np.mean(sachin_by_25s,axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [99]:
np.mean(sachin[sachin >= 100])

125.0

In [100]:
np.percentile(india,[25,50,75,100])

array([175., 216., 273., 499.])

In [101]:
qrs = np.percentile(india, [25, 50, 75, 100])

In [103]:
qrs = qrs.reshape(4, 1)

In [104]:
indices = india < qrs

In [105]:
sachin[indices[1, :]]

array([ 11.,  18.,  14.,   4.,   0.,  21.,  62.,   2.,  46.,  65.,   0.,
        39.,  48.,   3.,  11.,   5.,  65.,  27.,   7.,   2.,  28.,   6.,
         7.,   3.,   2.,   4., 100.,  15.,  32.,  40.,   0.,   5.,   8.,
         5.,   0.,  30.,  37.,  89.,   0.,  52.,  93.,  45.,   0.,   1.,
         0.,   3.,   0.,  81.,  78.,   6.,  28.,  13.,  93.,   2.,  36.,
         2.,  12.,  19.,  34.,   2.,  82.,   0.,   6.,   8.,  23.,  35.,
        74., 117.,  49.,  64.,   5.,  17.,   0.,  44.,  68.,   3.,  47.,
        17.,  35.,  88., 127.,   0.,  45.,  33., 110.,   7.,  25.,   9.,
         2.,  11.,  17.,   1.,  45.,   9.,  67.,  10.,  55.,   0.,   1.,
       101.,  23.,   1.,  41.,   1.,  28.,   2.,  22.,  25.,   0.,  27.,
        40.])

In [106]:
for i in range(4):
    print(i, np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146
